version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    #    ports:
    #      - "80:80"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
    volumes:
      - ~/webRoot/:/var/www/html/:ro
      - ./nginx/etc/nginx/vhost:/etc/nginx/vhost:ro
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/etc/nginx/laravel.conf:/etc/nginx/laravel.conf:ro
      - ./nginx/etc/nginx/enable-php.conf:/etc/nginx/enable-php.conf:ro
      - ./nginx/etc/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
  php:
    build: ./php
    container_name: php
    environment:
      - TZ=Asia/Shanghai
    expose:
      - 9000
    volumes:
      - ~/.ssh/:/root/.ssh/:ro
      - ~/webRoot/:/var/www/html/:rw
      - ./php/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
  mysql:
    image: mysql:5.7.18
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/var/lib/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data:rw
#  nsqlookupd:
#    image: nsqio/nsq
#    container_name: nsqlookupd
#    command: /nsqlookupd
#    ports:
#      - "4160:4160"
#      - "4161:4161"
#  nsqd:
#    image: nsqio/nsq
#    container_name: nsqd
#    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
#    depends_on:
#      - nsqlookupd
#    ports:
#      - "4150:4150"
#      - "4151:4151"
#  nsqadmin:
#    image: nsqio/nsq
#    container_name: nsqadmin
#    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
#    depends_on:
#      - nsqlookupd
#    ports:
#      - "4171:4171"
